In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("C:/Users/hppc2/Downloads/tested.csv")

In [5]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
413,False,False,False,False,False,True,False,False,False,False,True,False
414,False,False,False,False,False,False,False,False,False,False,False,False
415,False,False,False,False,False,False,False,False,False,False,True,False
416,False,False,False,False,False,True,False,False,False,False,True,False
417,False,False,False,False,False,True,False,False,False,False,True,False

In [6]:
df.isnull().min()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin          False
Embarked       False
dtype: bool

In [7]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [8]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [9]:
y=df[['PassengerId', 'Survived', 'Pclass','Age', 'SibSp','Parch','Fare']]

In [10]:
y

     PassengerId  Survived  Pclass   Age  SibSp  Parch      Fare
0            892         0       3  34.5      0      0    7.8292
1            893         1       3  47.0      1      0    7.0000
2            894         0       2  62.0      0      0    9.6875
3            895         0       3  27.0      0      0    8.6625
4            896         1       3  22.0      1      1   12.2875
..           ...       ...     ...   ...    ...    ...       ...
413         1305         0       3   NaN      0      0    8.0500
414         1306         1       1  39.0      0      0  108.9000
415         1307         0       3  38.5      0      0    7.2500
416         1308         0       3   NaN      0      0    8.0500
417         1309         0       3   NaN      1      1   22.3583

[418 rows x 7 columns]

In [11]:
from sklearn import preprocessing

In [12]:

minmax=preprocessing.MinMaxScaler()

In [13]:
x=minmax.fit_transform(y)

In [14]:
normalize=pd.DataFrame(x)

In [15]:
normalize

            0    1    2         3      4         5         6
0    0.000000  0.0  1.0  0.452723  0.000  0.000000  0.015282
1    0.002398  1.0  1.0  0.617566  0.125  0.000000  0.013663
2    0.004796  0.0  0.5  0.815377  0.000  0.000000  0.018909
3    0.007194  0.0  1.0  0.353818  0.000  0.000000  0.016908
4    0.009592  1.0  1.0  0.287881  0.125  0.111111  0.023984
..        ...  ...  ...       ...    ...       ...       ...
413  0.990408  0.0  1.0       NaN  0.000  0.000000  0.015713
414  0.992806  1.0  0.0  0.512066  0.000  0.000000  0.212559
415  0.995204  0.0  1.0  0.505473  0.000  0.000000  0.014151
416  0.997602  0.0  1.0       NaN  0.000  0.000000  0.015713
417  1.000000  0.0  1.0       NaN  0.125  0.111111  0.043640

[418 rows x 7 columns]

In [16]:
normalize1=pd.DataFrame(x,columns=['PassengerId', 'Survived', 'Pclass','Age', 'SibSp','Parch','Fare'])

In [17]:
normalize1

     PassengerId  Survived  Pclass       Age  SibSp     Parch      Fare
0       0.000000       0.0     1.0  0.452723  0.000  0.000000  0.015282
1       0.002398       1.0     1.0  0.617566  0.125  0.000000  0.013663
2       0.004796       0.0     0.5  0.815377  0.000  0.000000  0.018909
3       0.007194       0.0     1.0  0.353818  0.000  0.000000  0.016908
4       0.009592       1.0     1.0  0.287881  0.125  0.111111  0.023984
..           ...       ...     ...       ...    ...       ...       ...
413     0.990408       0.0     1.0       NaN  0.000  0.000000  0.015713
414     0.992806       1.0     0.0  0.512066  0.000  0.000000  0.212559
415     0.995204       0.0     1.0  0.505473  0.000  0.000000  0.014151
416     0.997602       0.0     1.0       NaN  0.000  0.000000  0.015713
417     1.000000       0.0     1.0       NaN  0.125  0.111111  0.043640

[418 rows x 7 columns]